#Este es para que Hibernate creara la tabla sino existe ahora con Migraciones es diferente
#spring.jpa.hibernate.ddl-auto=update
#Este es la nueva manera
spring.jpa.hibernate.ddl-auto=validate
spring.application.name=DanielVelasco
server.port=8080
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG